version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: adminadmin
      WORDPRESS_DB_PASSWORD: passwordpassword
      WORDPRESS_DB_NAME: bigwallets_db
    volumes:
      - wordpress:/var/www/html
    links: 
      - db:db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: bigwallets_db
      MYSQL_USER: adminadmin
      MYSQL_PASSWORD: passwordpassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: